### ISSUE TITLE
bezier在vs上无法编译通过

### ISSUE THREAD

**Issue by suljaxm** [zl03jsj/hand-draw-algorithm#1]
通过vs2017打开bezier.sln，一堆不能用，不知道是什么原因，下面是我打开后的效果
![2017-12-30_204221](https://user-images.githubusercontent.com/32708865/34454250-53aa3d5a-eda2-11e7-9c44-c0bf873e1b58.png)
是我哪方面操作出现了问题呢？

**Comment by zl03jsj** [comment]
Algorithm.cpp,Algorithm.h,bezier.h,bezier.cpp这几个文件都是不需要的,我只是放在那里做备份.你可以删除.
另外看你的错误, windows.h, 和 gidplus.h 没有找到, 都是windows sdk中自带的头文件.
下面的错误, 都是因为没有头文件中的类型而导致的,.

下次这种问题我就不回复你啦. 👎

**Comment by suljaxm** [comment]
哦哦 谢谢你~

**Comment by suljaxm** [comment]
@zl03jsj 哦哦， 非常感谢你~

**Comment by zl03jsj** [comment]
问题解决了？ 好用吗？

发自我的 iPhone

**Comment by suljaxm** [comment]
嗯嗯 解决了 看效果挺好的～

在 2018年1月2日，下午5:47，zl <notifications@github.com<mailto:notifications@github.com>> 写道：

问题解决了？ 好用吗？

发自我的 iPhone
